{
  "build": {
    "beforeBuildCommand": "",
    "beforeDevCommand": "",
    "devPath": "../src",
    "distDir": "../src"
  },
  "package": {
    "productName": "Aegis Installer",
    "version": "0.1.0"
  },
  "tauri": {
    "bundle": {
      "identifier": "com.nogap.installer"
    },
    "windows": [
      {
        "title": "Aegis USB Authority Installer",
        "width": 900,
        "height": 700
      }
    ]
  }
}
